CREATE DATABASE customer_behaviour;
SHOW DATABASES;
USE customer_behaviour;
SHOW TABLES;
SELECT * FROM customer;
SELECT * FROM customer LIMIT 10;
SELECT COUNT(*) FROM customer;

# Q1. What is the total revenue generated by male vs. female customers?
SELECT gender , SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;


# Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id,purchase_amount
FROM customer
WHERE discount_applied='Yes'
 AND purchase_amount>=( SELECT AVG(purchase_amount) FROM customer);


# Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating),2) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;


# Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type, 
ROUND(AVG(purchase_amount),2)
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;


# Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,
COUNT(customer_id) AS total_customers,
ROUND(AVG(purchase_amount),2) AS avg_spend,
ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC;


# Q6. What are the top 3 most purchased products within each category?
WITH item_counts AS (
	SELECT 
		category,
		item_purchased,
		COUNT(customer_id) AS total_orders,
		ROW_NUMBER() over (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
	FROM customer
	GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased ,total_orders
FROM item_counts
WHERE item_rank <= 3


# Q7. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
	subscription_status,
	COUNT(customer_id) AS total_customers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


# Q8. What is the revenue contribution of each age group
SELECT age_group,
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;

